from pathlib import Path
from datetime import datetime

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
)


# ===========================
# Directories
# ===========================

OUTPUT_DIR = Path("backend/reports")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

LOGO_PATH = Path("backend/assets/logo.png")
print("Logo path:", LOGO_PATH.resolve())
print("Logo exists:", LOGO_PATH.exists())

# ===========================
# PDF Generator
# ===========================

def generate_pdf(filename, findings):

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    report_id = f"DENT-{timestamp}"

    pdf_path = OUTPUT_DIR / f"DentAI_Report_{timestamp}.pdf"

    doc = SimpleDocTemplate(str(pdf_path))

    styles = getSampleStyleSheet()

    elements = []

    # ===========================
    # Logo
    # ===========================

    if LOGO_PATH.exists():
        logo = Image(str(LOGO_PATH))
        logo.drawWidth = 1.2 * inch
        logo.drawHeight = 1.2 * inch
        elements.append(logo)

    elements.append(Spacer(1, 0.2 * inch))

    # ===========================
    # Title
    # ===========================

    elements.append(
        Paragraph(
            "<font size='22'><b>DentAI Clinical Report</b></font>",
            styles["Title"]
        )
    )

    elements.append(Spacer(1, 0.2 * inch))

    # ===========================
    # Report Information
    # ===========================

    elements.append(
        Paragraph(
            f"<b>Report ID:</b> {report_id}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Date:</b> {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            styles["BodyText"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Image:</b> {filename}",
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 0.3 * inch))

    # ===========================
    # Findings Section
    # ===========================

    elements.append(
        Paragraph(
            "<b>Clinical Findings</b>",
            styles["Heading2"]
        )
    )

    elements.append(Spacer(1, 0.1 * inch))

    if len(findings) == 0:

        elements.append(
            Paragraph(
                "No abnormalities were detected.",
                styles["BodyText"]
            )
        )

    else:

        for finding in findings:

            elements.append(
                Paragraph(
                    f"<b>{finding['class']}</b>",
                    styles["Heading3"]
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Detected:</b> {finding['count']} time(s)",
                    styles["BodyText"]
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Confidence:</b> {finding['confidence']:.2f}",
                    styles["BodyText"]
                )
            )

            elements.append(
                Paragraph(
                    f"<b>Description:</b> {finding['description']}",
                    styles["BodyText"]
                )
            )

            elements.append(
                Paragraph(
                    "<b>Recommendations:</b>",
                    styles["BodyText"]
                )
            )

            for recommendation in finding["recommendation"]:

                elements.append(
                    Paragraph(
                        f"• {recommendation}",
                        styles["BodyText"]
                    )
                )

            elements.append(Spacer(1, 0.2 * inch))

    # ===========================
    # Disclaimer
    # ===========================

    elements.append(Spacer(1, 0.2 * inch))

    elements.append(
        Paragraph(
            "<b>Disclaimer</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            "This report has been generated by DentAI using artificial intelligence. "
            "It is intended solely for educational and research purposes and must not "
            "be considered a substitute for professional dental diagnosis, clinical "
            "judgment, or treatment planning. Please consult a qualified dentist for "
            "an official diagnosis.",
            styles["BodyText"]
        )
    )

    # ===========================
    # Build PDF
    # ===========================

    doc.build(elements)

    return pdf_path